name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ 새 기능'
    semver-increment: minor
    when:
      labels:
        - 'feat'
        - 'feature'
  - title: '🐛 버그 수정'
    semver-increment: patch
    when:
      labels:
        - 'fix'
        - 'bug'
  - title: '🎨 디자인 변경'
    semver-increment: patch
    when:
      labels:
        - 'design'
        - 'ui'
  - title: '⚡️ 성능 개선'
    semver-increment: patch
    when:
      labels:
        - 'perf'
        - 'performance'
  - title: '🔧 내부 작업'
    when:
      labels:
        - 'chore'
        - 'refactor'
        - 'ci'
        - 'test'
        - 'docs'
  - type: pre-exclude
    when:
      labels:
        - 'skip-changelog'
  - type: version-resolver
    semver-increment: major
    when:
      labels:
        - 'breaking-change'
  - type: version-resolver
    semver-increment: patch

no-changes-template: '변경사항 없음'

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

template: |
  ## 변경사항

  $CHANGES
